name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      environment_url:
        description: 'URL of the environment to run tests in'
        required: true
        default: 'https://www.saucedemo.com/'

      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install 

      - name: Set environment variable
        run: echo "ENVIRONMENT_URL=${{ github.event.inputs.environment_url }}" >> $GITHUB_ENV
             

      - name: Run Playwright tests
        run: npx playwright test
        env:
          BASE_URL: ${{ env.ENVIRONMENT_URL }}
          
